export default [
  {
    level: 1,
    bossChance: 3,
    startingPosition: [4, 1],
    layout: [
      [
        null,
        { level: 3, loot: false, boss: true },
        null,
        null,
        null,
        null,
      ],
      [
        { level: 3, loot: false, boss: true },
        { level: 3, loot: 3, boss: false },
        { level: 3, loot: false, boss: false },
        { level: 2, loot: false, boss: false },
        { level: 1, loot: false, boss: false },
        { level: 1, loot: false, boss: false },
      ],
      [
        null,
        { level: 3, loot: false, boss: true },
        null,
        null,
        { level: 3, loot: 3, boss: false },
        { level: 1, loot: false, boss: false },
      ],
      [
        null,
        null,
        null,
        { level: 2, loot: false, boss: false },
        { level: 1, loot: false, boss: false },
        { level: 1, loot: false, boss: false },
      ],
      [
        null,
        { start: true },
        { level: 1, loot: false, boss: false },
        { level: 1, loot: false, boss: false },
        { level: 2, loot: false, boss: false },
        { level: 1, loot: 1, boss: false },
      ],
    ],
  },
  {
    level: 2,
    bossChance: 3,
    startingPosition: [3, 3],
    layout: [
      [
        null,
        null,
        null,
        null,
        { level: 1, loot: 1, boss: false },
        null,
        null,
        null,
      ],
      [
        { level: 3, loot: false, boss: true },
        { level: 2, loot: false, boss: false },
        { level: 2, loot: false, boss: false },
        null,
        { level: 3, loot: false, boss: false },
        { level: 3, loot: false, boss: false },
        { level: 3, loot: false, boss: true },
        null,
      ],
      [
        null,
        { level: 3, loot: false, boss: false },
        { level: 2, loot: false, boss: false },
        { level: 1, loot: false, boss: false },
        { level: 2, loot: false, boss: false },
        { level: 2, loot: false, boss: false },
        null,
        null,
      ],
      [
        null,
        { level: 2, loot: 2, boss: false },
        null,
        { start: true },
        { level: 1, loot: false, boss: false },
        null,
        null,
        null,
      ],
      [
        null,
        null,
        null,
        null,
        { level: 1, loot: false, boss: false },
        { level: 1, loot: false, boss: false },
        null,
        null,
      ],
      [
        null,
        null,
        null,
        { level: 3, loot: 3, boss: false },
        { level: 3, loot: false, boss: false },
        { level: 1, loot: false, boss: false },
        { level: 1, loot: false, boss: false },
        { level: 3, loot: false, boss: true },
      ],
    ],
  },
];
