export default [
  {
    title: 'Blazing Effigy',
    description: 'All of your attacks inflict Burn.',
    level: 3,
    phase: 'Main',
    equipment: true,
    cost: 4,
    id: 1,
  },
  {
    title: 'Blood Amulet',
    description: 'Whenever your Defense Roll is activated, steal 1 Health.',
    level: 3,
    phase: 'Main',
    equipment: true,
    cost: 4,
    id: 2,
  },
  {
    title: 'Get That Outta Here IV',
    description: 'Remove up to two status effect tokens from a chosen player.',
    level: 4,
    phase: 'Instant',
    equipment: false,
    cost: 0,
    id: 3,
  },
  {
    title: 'Treasure Hunter III',
    description: 'Gain a level 3 loot.',
    level: 3,
    phase: 'Main',
    equipment: false,
    cost: 2,
    id: 4,
  },
  {
    title: 'Tip It II',
    description: 'Increase or decrease any die by the value of 1 (1 cannot be decreased, 6 cannot be increased)',
    level: 3,
    phase: 'Instant',
    equipment: false,
    cost: 0,
    id: 5,
  },
  {
    title: 'Getting Paid II',
    description: 'Gain 3CP.',
    level: 2,
    phase: 'Instant',
    equipment: false,
    cost: 0,
    id: 6,
  },
  {
    title: 'Helping Hand II',
    description: 'Select one of your opponent\'s dice and force them to re-roll it.',
    level: 2,
    phase: 'Roll',
    equipment: false,
    cost: 0,
    id: 7,
  },
  {
    title: 'Samesies II',
    description: 'Change the value of one of your dice to be identical to the value of another one of your dice. (that was rolled within the same phase and for the same purpose)',
    level: 2,
    phase: 'Roll',
    equipment: false,
    cost: 0,
    id: 8,
  },
  {
    title: 'One More Time II',
    description: 'A chosen player may perform a re-roll of up to five dice during the Offensive Roll Phase.',
    level: 1,
    phase: 'Roll',
    equipment: false,
    cost: 0,
    id: 9,
  },
  {
    title: 'Link',
    description: 'You and a chosen teammate each roll 1 die: The player with the highest value draws 2 cards, while the other player recieves 2 dmg. On a tie, both players draw 2 cards.',
    level: 1,
    phase: 'Main',
    equipment: false,
    cost: 1,
    id: 10,
  },
  {
    title: 'Transference II',
    description: 'Transfer 1 status effect token from a chosen player to another chosen player.',
    level: 1,
    phase: 'Main',
    equipment: false,
    cost: 1,
    id: 11,
  },
  {
    title: 'Vegas Baby II',
    description: 'Roll 1 die: Gain 1/2 the value as CP (rounded up). If desired, this die may be re-rolled 1 time.',
    level: 1,
    phase: 'Main',
    equipment: false,
    cost: 0,
    id: 12,
  },
  {
    title: 'Vegas Baby III',
    description: 'Roll 1 die: Gain 1 + 1/2 the value as CP (rounded up).',
    level: 2,
    phase: 'Main',
    equipment: false,
    cost: 0,
    id: 13,
  },
  {
    title: 'What Status Effects II',
    description: 'Remove all status effect tokens from a chosen player.',
    level: 1,
    phase: 'Main',
    equipment: false,
    cost: 1,
    id: 14,
  },
  {
    title: 'Try, Try again II',
    description: 'You or a chosen teammate may re-roll up to two dice. (can be the same dice twice in a row or two different die)',
    level: 1,
    phase: 'Roll',
    equipment: false,
    cost: 0,
    id: 15,
  },
  {
    title: 'Try, Try again III',
    description: 'You or a chosen teammate may re-roll up to three dice. (can be the same dice three times in a row or three different die)',
    level: 3,
    phase: 'Roll',
    equipment: false,
    cost: 1,
    id: 16,
  },
  {
    title: 'Codex II',
    description: 'Search your deck for any card and put it into your hand. Then shuffle your deck.',
    level: 1,
    phase: 'Roll',
    equipment: false,
    cost: 0,
    id: 17,
  },
  {
    title: 'Health Potion',
    description: 'A chosen Player Heals 2.',
    level: 1,
    phase: 'Instant',
    equipment: false,
    cost: 1,
    id: 18,
  },
  {
    title: 'Health Potion II',
    description: 'A chosen Player Heals 3.',
    level: 2,
    phase: 'Instant',
    equipment: false,
    cost: 1,
    id: 19,
  },
  {
    title: 'Health Potion III',
    description: 'A chosen Player Heals 4.',
    level: 3,
    phase: 'Instant',
    equipment: false,
    cost: 1,
    id: 20,
  },
  {
    title: 'Campfire',
    description: 'Draw 1 card. Each of your teammates draws 1 card.',
    level: 3,
    phase: 'Instant',
    equipment: false,
    cost: 2,
    id: 21,
  },
  {
    title: 'Leather Armor',
    description: 'You may re-roll any 1 die that was rolled as a part of your defensive ability.',
    level: 3,
    phase: 'Main',
    equipment: true,
    cost: 2,
    id: 22,
  },
  {
    title: 'So Wild II',
    description: 'Change the value of any one die.',
    level: 2,
    phase: 'Roll',
    equipment: false,
    cost: 1,
    id: 23,
  },
  {
    title: 'Twice As Wild II',
    description: 'Change the values of any two die to anything you want.',
    level: 2,
    phase: 'Roll',
    equipment: false,
    cost: 2,
    id: 24,
  },
  {
    title: 'Twice As Wild III',
    description: 'Change the values of any two die to anything you want.',
    level: 3,
    phase: 'Roll',
    equipment: false,
    cost: 1,
    id: 25,
  },
  {
    title: 'Twice As Wild IV',
    description: 'Change the values of any two die to anything you want.',
    level: 4,
    phase: 'Roll',
    equipment: false,
    cost: 0,
    id: 26,
  },
  {
    title: 'Six-It III',
    description: 'Change the outcome of any one of your dice to a 6.',
    level: 4,
    phase: 'Roll',
    equipment: false,
    cost: 0,
    id: 27,
  },
  {
    title: 'Strength Serum II',
    description: 'A chosen player gains crit. Draw 1 card.',
    level: 2,
    phase: 'Main',
    equipment: false,
    cost: 2,
    id: 28,
  },
  {
    title: 'Regenerating Orb II',
    description: 'During your Upkeep Phase, roll 1 die: On 4-6, Heal 2.',
    level: 3,
    phase: 'Main',
    equipment: false,
    cost: 1,
    id: 29,
  },
  {
    title: 'Recall Scroll III',
    description: 'Choose 1 card from your discard pile and put it into your hand.',
    level: 3,
    phase: 'Instant',
    equipment: false,
    cost: 1,
    id: 30,
  },
  {
    title: 'Greed II',
    description: 'Increase the boss CP by 4. Gain a level 1 loot.',
    level: 2,
    phase: 'Instant',
    equipment: false,
    cost: 0,
    id: 31,
  },
];
