export default [
  {
    level: 1,
    title: 'Vault I',
    playerCP: 1,
    gold: 0,
    bossCP: 1,
    enemyType: 1,
    description: 'Gain green loot, Alternatively roll 1 die. On 1-3, gain nothing. On 4-6 gain blue chest.',
  },
  {
    level: 1,
    title: 'Lonely Tower I',
    playerCP: 0,
    gold: 0,
    bossCP: 2,
    enemyType: 1,
    description: 'You may play an upgrade card from your hand that costs 2CP or less for free.',
  },
  {
    level: 1,
    title: 'Mirage I',
    playerCP: 0,
    gold: 0,
    bossCP: 1,
    enemyType: 0,
    description: 'Roll 1 die: On 1-2 gain concussion. On 3-4, spawn a level 1 monster. On 5-6, gain 1CP.',
  },
  {
    level: 1,
    title: 'Stained Spire I',
    playerCP: 0,
    gold: 1,
    bossCP: 3,
    enemyType: 0,
    description: 'You may recieve 2 undefendable dmg to reveal an adjacent tile. If desired, you may move to this tile as if you had explored it',
  },
  {
    level: 1,
    title: 'Mountain of Salt I',
    playerCP: 0,
    gold: 0,
    bossCP: 1,
    enemyType: 0,
    description: 'Spawn a level 1 minion. Alternatively, roll 1 die: On 1-3, Spawn a level 2 minion. On 4-6, gain 2 gold.',
  },
  {
    level: 1,
    title: 'Ivory Woods I',
    playerCP: 0,
    gold: 1,
    bossCP: 1,
    enemyType: 1,
    description: 'Gain Backstrike & Wither.',
  },
  {
    level: 1,
    title: 'Everglades I',
    playerCP: 0,
    gold: 0,
    bossCP: 1,
    enemyType: 0,
    description: 'Spawn a level 1 minion. Alternatively, Spawn a level 2 minion and gain a green loot.',
  },
  {
    level: 1,
    title: 'Alley I',
    playerCP: 1,
    gold: 0,
    bossCP: 1,
    enemyType: 1,
    description: 'Discard 1 card of your choosing.',
  },
  {
    level: 2,
    title: 'Emerald Shoal II',
    playerCP: 1,
    gold: 0,
    bossCP: 2,
    enemyType: 2,
    description: 'Remove all status effects from the active player.',
  },
  {
    level: 2,
    title: 'Scorched Mesa II',
    playerCP: 0,
    gold: 2,
    bossCP: 2,
    enemyType: 2,
    description: 'Recieve 2 Dmg.',
  },
  {
    level: 2,
    title: 'Toll Bridge II',
    playerCP: 0,
    gold: 0,
    bossCP: 2,
    enemyType: 0,
    description: 'Pay 3CP or else Spawn a level 2 minion.',
  },
  {
    level: 2,
    title: 'Thorn Road II',
    playerCP: 0,
    gold: 0,
    bossCP: 2,
    enemyType: 0,
    description: 'Roll 1 die: On 1-2, gain Entangle. On 3-5, gain Barbed Vine. On 6, gain 2 gold.',
  },
  {
    level: 2,
    title: 'Bazaar II',
    playerCP: 0,
    gold: 0,
    bossCP: 3,
    enemyType: 2,
    description: 'You may pay 2CP to gain a blue treasure. If desired, you may sell cards at this time.',
  },
  {
    level: 2,
    title: 'Poison Bog II',
    playerCP: 2,
    gold: 2,
    bossCP: 0,
    enemyType: 2,
    description: 'Gain 2 Poison.',
  },
  {
    level: 3,
    title: 'Solarium III',
    playerCP: 0,
    gold: 3,
    bossCP: 3,
    enemyType: 3,
    description: 'All Heroes are inflicted with Blind.',
  },
  {
    level: 3,
    title: 'Volcano III',
    playerCP: 0,
    gold: 3,
    bossCP: 3,
    enemyType: 3,
    description: 'All Heroes are inflicted with Burn.',
  },
  {
    level: 3,
    title: 'Citadel III',
    playerCP: 3,
    gold: 0,
    bossCP: 3,
    enemyType: 3,
    description: 'All heroes choose and discard half their cards (rounded up). Then draw 1 card.',
  },
  {
    level: 3,
    title: 'Subterrainium III',
    playerCP: 0,
    gold: 3,
    bossCP: 5,
    enemyType: 0,
    description: 'You may pay 2CP to place 1 card from your discard pile into your hand.',
  },
  {
    level: 3,
    title: 'Town Center III',
    playerCP: 0,
    gold: 0,
    bossCP: 3,
    enemyType: 3,
    description: 'Discard 1 random card. All other heroes draw 1 card.',
  },
  {
    level: 3,
    title: 'Twisted Roots III',
    playerCP: 0,
    gold: 3,
    bossCP: 3,
    enemyType: 3,
    description: 'All players are inflicted with Entangle',
  },
  {
    level: 3,
    title: 'Pensieve Pool III',
    playerCP: 0,
    gold: 0,
    bossCP: 4,
    enemyType: 0,
    description: 'You may choose to pay 1CP to heal 3 or pay 3CP to heal all players 3.',
  },
  {
    level: 3,
    title: 'Gunslinger Grotto',
    playerCP: 3,
    gold: 0,
    bossCP: 3,
    enemyType: 4,
    description: 'Spawn the Fallen Gunslinger',
  },
  {
    level: 3,
    title: 'Barbarian Brawl',
    playerCP: 3,
    gold: 0,
    bossCP: 3,
    enemyType: 4,
    description: 'Spawn the Fallen Barbarian',
  },
];
